spring:
  application:
    name: registry
  aop:
    proxy-target-class: true
  profiles:
    active: dev
  resources:
    static-locations: classpath:static
  lifecycle:
    timeout-per-shutdown-phase: 30s

  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true
        max-retries-on-next-service-instance: 1
        max-retries-on-same-service-instance: 0
        retry-on-all-operations: false
        retryable-status-codes: [ 203,500,408,504 ]
        backoff:
          enabled: true
          jitter: 0.5
          min-backoff: 5ms
          max-backoff: 10ms
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=1024,expireAfterWrite=5s
        capacity: 1024
        ttl: 5s

server:
  shutdown: graceful

logging:
  config: classpath:config/log4j2.xml